### PR TITLE
Disable StrictHostKeyCheck

### PR DESCRIPTION
**Pull request by mynamewastaken**

### CODE REVIEW

**Comment by gpetrousov** [comment]
@mynamewastaken - Thanks for authoring, can you please do a rebase against master and fix errors? 😁

**Comment by mynamewastaken** [comment]
@gpetrousov I can do the rebase. Which errors are you referring to?

Edit - Ah, I see. You've added Travis since. :)

**Comment by mynamewastaken** [comment]
Closes #1

**Comment by gpetrousov** [comment]
Thanks :muscle:

**Pull request merged**
